spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: a
  sql:
    init:
      schema-locations: classpath:db/db-schema.sql
      data-locations: classpath:db/initial-data.sql
  security:
    user:
      name: user@user.lt
      password: user
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true